In [1]:
import pandas as pd
import os , sys
sys.path.append(os.path.abspath('../scripts'))

In [2]:
import preprocessing_each_columns as pec

### loading the data set first

In [3]:
df = pd.read_csv('../data/preprocessed_data-preprocessed_data.csv')

# preprocessing the Location Column

In [4]:
df.head()

,Name,Type of Activity,Description,Location,OpeningTimes,OpeningTime,ClosingTime,Duration,Is_Special_Schedule,Fee_Adult_EGP,Fee_kid_EGP
0,Al Azhar Park,Outdoor Activity,A large park with beautiful gardens and recrea...,Cairo,9:00 AM -10:00 PM,9:00,22:00,13,FALSE,10.0,NaN
1,Aquarium Grotto Park,Outdoor Activity,A park featuring an aquarium and scenic views.,"Zamalek, Cairo",9:00 AM - 5:30 PM,9:00,17:30,8.5,FALSE,20.0,NaN
2,Family Park,Outdoor Activity,A family-friendly park with various activities.,New Cairo,9:00 AM -12:00 AM,9:00,0:00,21,FALSE,160.0,460.0
3,Nile Cruise (Felucca),Outdoor Activity,Sail the Nile River at sunset.,"Maadi, Zamalek",9:00 AM -12:00 AM,9:00,0:00,21,FALSE,24500.0,NaN
4,Zawya,Movie Screenings & Art Performances,Art-house cinema screening alternative films a...,"15 Emad El-Deen, Downtown",Check weekly schedule,NaN,NaN,NaN,TRUE,100.0,NaN

In [5]:
df['Location'].value_counts()

Location
Cairo                                                            10
Cairo Festival City Mall                                          4
Giza, Cairo                                                       4
Nile River, Cairo                                                 2
Various locations                                                 2
Americana Plaza – Sheikh Zayed                                    2
Dandy Mega Mall – Cairo/Alex Desert Road                          2
1 Palestine St., El Bandar Mall – Maadi                           2
Dandy Mega Mall – Cairo/Alex Desert Road, 6th of October City     2
Salah Salem Street, Heliopolis                                    2
3 Skies Plaza, 5th Settlement – New Cairo                         2
46 El-Nozha, Heliopolis                                           2
Street no. 9 in front of Pizza Hut – Maadi                        2
5th Settlement, Concord Plaza Mall                                2
10 Etehaad Al Mohamin St., Garden City                            2
8 Sesostris street, Heliopolis                                    2
Palm Strip Mall, 6th of October City                              2
Heliopolis, Cairo                                                 2
Zamalek, Cairo                                                    2
Obour City, Cairo                                                 2
Maryouteya Road, Giza                                             2
Cairo Festival City, Cairo                                        2
30 km southwest of Cairo                                          2
Abu Sir, Cairo                                                    2
Porto Cairo, Cairo                                                2
Various locations in Cairo                                        2
City Stars Mall, Cairo                                            2
El-Gamaleya, Cairo                                                2
Mall of Arabia, Cairo                                             2
Maadi City Center, Cairo Festival City Mall, Mall of Egypt        2
Mirage Mall – Suez Road & Mall of Arabia, 6th of October City     2
City Square Mall, Al Rehab                                        2
258 A, Anas Ebn Malek Street – New Cairo                          2
New Cairo                                                         2
Maadi, Zamalek                                                    2
15 Emad El-Deen, Downtown                                         2
12 Mohamed Anis St., Zamalek                                      2
Islamic Cairo                                                     2
Mall of Egypt, 6th of October City                                2
Obour City                                                        2
3 Skies Plaza, 5th Settlement                                     2
The Field Maadi Sports Community Club                             2
Point 90 Mall, New Cairo & Avenue Mall, Obour City                2
Cairo Festival City, 5th Settlement                               2
Inside Mazar Mall, 6th of October City                            2
Gate 1, Al-Hezam El-Akhdar, 6th of October                        2
Dandy Mega Mall, 6th of October City                              2
MOVING TO A NEW LOCATION                                          2
New Cairo Club, 5th Settlement                                    2
Various locations in Maadi                                        2
54 Mohi El-Din Abo Al Ezz street, Dokki                           2
Al Guezira Plaza, Sheikh Zayed                                    2
104 Omar Ebn El-Khattab Street, Heliopolis                        2
34 Street 206, Degla – Maadi                                      2
56 Al Bostan St, Sheikh Zayed                                     2
B311, 90th Street, New Cairo                                      2
5 Abou El-Feda St., Zamalek                                       2
4, 216 Street, Victory Square – Maadi                             2
Location                                                          1
Villa Pax, Imbaba, Cairo                                          1
Name: count, dtype: int64

In [6]:
df = pec.processing_location_col(df)

INFO:preprocessing_each_columns:preprocessing the location column

In [7]:
df['Location'].value_counts()

Location
Cairo                  16
New Cairo              14
Maadi                  14
Heliopolis             10
Cairo Festival City     8
Dandy Mega Mall         6
Zamalek                 6
Sheikh Zayed            6
Giza                    6
Multiple Locations      4
Obour City              4
Garden City             2
Abu Sir                 2
El-Gamaleya             2
Mall of Arabia          2
City Stars Mall         2
Palm Strip Mall         2
Porto Cairo             2
Al Rehab                2
Concord Plaza Mall      2
Maadi City Center       2
Mirage Mall             2
Dokki                   2
Unknown Location        2
6th of October City     2
Mazar Mall              2
Mall of Egypt           2
Downtown                2
Location                1
Imbaba                  1
Name: count, dtype: int64

In [8]:
df.head()

,Name,Type of Activity,Description,Location,OpeningTimes,OpeningTime,ClosingTime,Duration,Is_Special_Schedule,Fee_Adult_EGP,Fee_kid_EGP
0,Al Azhar Park,Outdoor Activity,A large park with beautiful gardens and recrea...,Cairo,9:00 AM -10:00 PM,9:00,22:00,13,FALSE,10.0,NaN
1,Aquarium Grotto Park,Outdoor Activity,A park featuring an aquarium and scenic views.,Zamalek,9:00 AM - 5:30 PM,9:00,17:30,8.5,FALSE,20.0,NaN
2,Family Park,Outdoor Activity,A family-friendly park with various activities.,New Cairo,9:00 AM -12:00 AM,9:00,0:00,21,FALSE,160.0,460.0
3,Nile Cruise (Felucca),Outdoor Activity,Sail the Nile River at sunset.,Maadi,9:00 AM -12:00 AM,9:00,0:00,21,FALSE,24500.0,NaN
4,Zawya,Movie Screenings & Art Performances,Art-house cinema screening alternative films a...,Downtown,Check weekly schedule,NaN,NaN,NaN,TRUE,100.0,NaN

In [9]:
df.to_csv('../data/final_touristData.csv' , index=False)

### recommendation model sample

In [10]:
# Function to allocate budget
def allocatae_budget(total_budget, num_days):
    daily_budget = total_budget / num_days
    budget_allocation = {
        'transportation': daily_budget * 0.20,
        'activities' : daily_budget * 0.50,
        'restaurants' : daily_budget * 0.30,
        'hotels':total_budget * 0.20/num_days # Spread hotel cost over days
    } 
    return budget_allocation

In [11]:
# Function to get dailt recommendations
def get_daily_recommendations(df,location , travelers , interests,budget_allocation,num_days):
    daily_plans = []
    for day in range(num_days):
        # filter recommendations for each dat
        filtered_data = data[
            (df['Location'] == location)&
            (df[''])
        ]

In [12]:
data = pd.read_csv('../data/final_touristData.csv')

In [13]:
data.head()

,Name,Type of Activity,Description,Location,OpeningTimes,OpeningTime,ClosingTime,Duration,Is_Special_Schedule,Fee_Adult_EGP,Fee_kid_EGP
0,Al Azhar Park,Outdoor Activity,A large park with beautiful gardens and recrea...,Cairo,9:00 AM -10:00 PM,9:00,22:00,13,FALSE,10.0,NaN
1,Aquarium Grotto Park,Outdoor Activity,A park featuring an aquarium and scenic views.,Zamalek,9:00 AM - 5:30 PM,9:00,17:30,8.5,FALSE,20.0,NaN
2,Family Park,Outdoor Activity,A family-friendly park with various activities.,New Cairo,9:00 AM -12:00 AM,9:00,0:00,21,FALSE,160.0,460.0
3,Nile Cruise (Felucca),Outdoor Activity,Sail the Nile River at sunset.,Maadi,9:00 AM -12:00 AM,9:00,0:00,21,FALSE,24500.0,NaN
4,Zawya,Movie Screenings & Art Performances,Art-house cinema screening alternative films a...,Downtown,Check weekly schedule,NaN,NaN,NaN,TRUE,100.0,NaN