In [1]:
import pandas as pd
import os , sys
sys.path.append(os.path.abspath('../scripts'))

In [2]:
import preprocessing_each_columns as pec

### loading the data set first

In [3]:
df = pd.read_csv('../data/preprocessed_data - preprocessed_data.csv')

# preprocessing the Location Column

In [4]:
df.head()

,Name,Type of Activity,Description,Location,OpeningTimes,OpeningTime,ClosingTime,Duration,Is_Special_Schedule,Fee_Adult_EGP,Fee_kid_EGP
0,Al Azhar Park,Outdoor Activity,A large park with beautiful gardens and recrea...,Cairo,9:00 AM -10:00 PM,9:00,22:00,13.0,False,10.0,NaN
1,Aquarium Grotto Park,Outdoor Activity,A park featuring an aquarium and scenic views.,"Zamalek, Cairo",9:00 AM - 5:30 PM,9:00,17:30,8.5,False,20.0,NaN
2,Family Park,Outdoor Activity,A family-friendly park with various activities.,New Cairo,9:00 AM -12:00 AM,9:00,0:00,21.0,False,160.0,460.0
3,Nile Cruise (Felucca),Outdoor Activity,Sail the Nile River at sunset.,"Maadi, Zamalek",9:00 AM -12:00 AM,9:00,0:00,21.0,False,24500.0,NaN
4,Zawya,Movie Screenings & Art Performances,Art-house cinema screening alternative films a...,"15 Emad El-Deen, Downtown",Check weekly schedule,NaN,NaN,NaN,True,100.0,NaN

In [5]:
df['Location'].value_counts()

Location
Cairo                                                            5
Cairo Festival City Mall                                         2
Giza, Cairo                                                      2
New Cairo                                                        1
Maadi, Zamalek                                                   1
12 Mohamed Anis St., Zamalek                                     1
15 Emad El-Deen, Downtown                                        1
Islamic Cairo                                                    1
Mall of Egypt, 6th of October City                               1
Obour City                                                       1
Zamalek, Cairo                                                   1
The Field Maadi Sports Community Club                            1
Point 90 Mall, New Cairo & Avenue Mall, Obour City               1
Cairo Festival City, 5th Settlement                              1
Inside Mazar Mall, 6th of October City                           1
Gate 1, Al-Hezam El-Akhdar, 6th of October                       1
Dandy Mega Mall, 6th of October City                             1
MOVING TO A NEW LOCATION                                         1
New Cairo Club, 5th Settlement                                   1
Various locations in Maadi                                       1
54 Mohi El-Din Abo Al Ezz street, Dokki                          1
Al Guezira Plaza, Sheikh Zayed                                   1
104 Omar Ebn El-Khattab Street, Heliopolis                       1
34 Street 206, Degla – Maadi                                     1
56 Al Bostan St, Sheikh Zayed                                    1
B311, 90th Street, New Cairo                                     1
3 Skies Plaza, 5th Settlement                                    1
5 Abou El-Feda St., Zamalek                                      1
4, 216 Street, Victory Square – Maadi                            1
City Square Mall, Al Rehab                                       1
258 A, Anas Ebn Malek Street – New Cairo                         1
Maadi City Center, Cairo Festival City Mall, Mall of Egypt       1
Americana Plaza – Sheikh Zayed                                   1
Dandy Mega Mall – Cairo/Alex Desert Road                         1
Mirage Mall – Suez Road & Mall of Arabia, 6th of October City    1
Dandy Mega Mall – Cairo/Alex Desert Road, 6th of October City    1
Salah Salem Street, Heliopolis                                   1
3 Skies Plaza, 5th Settlement – New Cairo                        1
46 El-Nozha, Heliopolis                                          1
Street no. 9 in front of Pizza Hut – Maadi                       1
5th Settlement, Concord Plaza Mall                               1
10 Etehaad Al Mohamin St., Garden City                           1
1 Palestine St., El Bandar Mall – Maadi                          1
8 Sesostris street, Heliopolis                                   1
Various locations                                                1
Palm Strip Mall, 6th of October City                             1
Obour City, Cairo                                                1
Maryouteya Road, Giza                                            1
Cairo Festival City, Cairo                                       1
30 km southwest of Cairo                                         1
Abu Sir, Cairo                                                   1
Porto Cairo, Cairo                                               1
Various locations in Cairo                                       1
El-Gamaleya, Cairo                                               1
Mall of Arabia, Cairo                                            1
Heliopolis, Cairo                                                1
Nile River, Cairo                                                1
City Stars Mall, Cairo                                           1
Villa Pax, Imbaba, Cairo                                         1
Name: count, dtype: int64

In [6]:
df = pec.processing_location_col(df)

INFO:preprocessing_each_columns:preprocessing the location column

In [7]:
df['Location'].value_counts()

Location
Cairo                  8
New Cairo              7
Maadi                  7
Heliopolis             5
Cairo Festival City    4
Dandy Mega Mall        3
Giza                   3
Sheikh Zayed           3
Zamalek                3
Multiple Locations     2
Obour City             2
Downtown               1
Mall of Egypt          1
Dokki                  1
Unknown Location       1
6th of October City    1
Mazar Mall             1
Mirage Mall            1
Maadi City Center      1
Concord Plaza Mall     1
Al Rehab               1
Garden City            1
Palm Strip Mall        1
Abu Sir                1
Porto Cairo            1
El-Gamaleya            1
Mall of Arabia         1
City Stars Mall        1
Imbaba                 1
Name: count, dtype: int64

In [10]:
df.head()

,Name,Type of Activity,Description,Location,OpeningTimes,OpeningTime,ClosingTime,Duration,Is_Special_Schedule,Fee_Adult_EGP,Fee_kid_EGP
0,Al Azhar Park,Outdoor Activity,A large park with beautiful gardens and recrea...,Cairo,9:00 AM -10:00 PM,9:00,22:00,13.0,False,10.0,NaN
1,Aquarium Grotto Park,Outdoor Activity,A park featuring an aquarium and scenic views.,Zamalek,9:00 AM - 5:30 PM,9:00,17:30,8.5,False,20.0,NaN
2,Family Park,Outdoor Activity,A family-friendly park with various activities.,New Cairo,9:00 AM -12:00 AM,9:00,0:00,21.0,False,160.0,460.0
3,Nile Cruise (Felucca),Outdoor Activity,Sail the Nile River at sunset.,Maadi,9:00 AM -12:00 AM,9:00,0:00,21.0,False,24500.0,NaN
4,Zawya,Movie Screenings & Art Performances,Art-house cinema screening alternative films a...,Downtown,Check weekly schedule,NaN,NaN,NaN,True,100.0,NaN

### recommendation model sample

In [8]:
# Function to allocate budget
def allocatae_budget(total_budget, num_days):
    daily_budget = total_budget / num_days
    budget_allocation = {
        'transportation': daily_budget * 0.20,
        'activities' : daily_budget * 0.50,
        'restaurants' : daily_budget * 0.30,
        'hotels':total_budget * 0.20/num_days # Spread hotel cost over days
    } 
    return budget_allocation

In [9]:
# Function to get dailt recommendations
def get_daily_recommendations(df,location , travelers , interests,budget_allocation,num_days):
    daily_plans = []
    for day in range(num_days):
        # filter recommendations for each dat
        filtered_data = data[
            (df['Location'] == location)&
            (df[''])
        ]